name: JavaScript CI

on:
  pull_request:
    paths:
      - "javascript/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies and run tests
        run: |
          find javascript -maxdepth 1 -type d -exec sh -c 'cd {} && yarn install && yarn test' \;
