name: JavaScript CI

on:
  pull_request:
    paths:
      - "javascript/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [
            "freelancer-rates",
            "annalyns-infiltration",
            "hello-world",
            "lasagna",
          ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies and run tests
        run: |
          cd javascript/${{ matrix.package }}
          yarn install
          yarn test
